### ISSUE TITLE
Upbound Marketplace

### ISSUE THREAD

**Issue by gaima8** [vfarcic/crossplane-function-loop#1]
Outside of all the significant issues of maintenance, etc, is there any particular reason this isn't published to the upbound marketplace?
Seems like an really simple and **incredibly** useful feature to have available.

**Comment by vfarcic** [comment]
I made it very early when functions were just released. In the meantime, we got functions that allow us to work with quite a few languages and I'm not sure it makes sense to use this one any more. If you choose KCL, CUE, Go Templating, Python, or any other, you will get loops (among all other goodies they support).
